# Generated by Django 3.2.7 on 2021-10-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='author',
            field=models.CharField(default='пользователь', max_length=50, verbose_name='Пользователь'),
        ),
    ]
