# Generated by Django 3.2.7 on 2021-10-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_art_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='комментарий')),
                ('author', models.CharField(max_length=50, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AddField(
            model_name='art',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.comment', verbose_name='комментарии'),
        ),
    ]
