# Generated by Django 3.2.7 on 2021-10-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211014_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='art',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.art', verbose_name='номер комментария'),
        ),
    ]
