# Generated by Django 3.2.7 on 2021-10-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211015_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.art', verbose_name='номер комментария'),
        ),
    ]
